### ISSUE TITLE
RecyclerView inside NestedScrollView weird behavior

### ISSUE THREAD

**Issue by MitchDroid** [NoNews/NoPaginate#13]
Hi  @NoNews , 

I am using  noPaginate lib ti handle a list of accounts movements, if I use the recyclerView [alone] the onLoadMore listener works fine when a reach the last item of the list, but when a Try to use NestedScrollView with RecyclerView the onLoadMore is called before I scroll down.

I hope you can Help me about this issue.

Cheers.

PD: I need to use NestedScrollView in order to use CollapsinToolbarLayout.

**Comment by MitchDroid** [comment]
Hey @NoNews , please help me!

**Comment by NoNews** [comment]
Hi @MitchDroid, sorry for the late answer. I am on vacation now.

Do you really need to use _NestedScrollView_ in this case? 
You can use just _RecyclerView_ with scroll behavior, like this:
`app:layout_behavior="@string/appbar_scrolling_view_behavior"` (in RecyclerView) 
with custom _ViewHolders_ for other layout elements if it necessary  (it's really depends on layout, but in most cases it works).

I think using _RecyclerView_ with _NestedScrollView_  is not a good idea, because most of _RecyclerView_ scrolling functions are lost.

**Comment by MitchDroid** [comment]
Perfect @NoNews , thank you very much!
